# import astropy.constants as aconst
# import astropy.units as u
from datetime import datetime

import numpy as np
import unyt as u

CLOUD_RADIUS_FACTOR = 1.3
# m_H = aconst.m_p + aconst.m_e
mu = 0.59


def print_initial_conditions(
    length_unit, mass_unit, time_unit, rho_ambient, T_ambient, T_cloud, v_cloud
):
    unit_block = """<units>
code_length_cgs = {length_unit:.12e} # {len_unit_comment:.2}
code_mass_cgs   = {mass_unit:.12e} # {mass_unit_comment:.2}
code_time_cgs   = {time_unit:.12e} # {time_unit_comment:.2}""".format(
        length_unit=length_unit.to("cm").value,
        len_unit_comment=length_unit.to("kpc"),
        mass_unit=mass_unit.to("g").value,
        mass_unit_comment=mass_unit.to("Msun"),
        time_unit=time_unit.to("s").value,
        time_unit_comment=time_unit.to("Gyr"),
    )

    problem_block = """<problem/moving_cloud>
rho_ambient_mh_cm3 = {rho_ambient} # Density [m_H / cm3], just a check: defined as 1 in code units
T_ambient_K        = {T_ambient:e} # [K]
T_cloud_K          = {T_cloud:e} # [K]
velocity_cloud_km_s = {velocity_cloud} # Velocity in x direction [km / s]
cloud_radius_factor = {cloud_radius_factor}""".format(
        rho_ambient=(rho_ambient / u.mh).to("1 / cm**3").value,
        T_ambient=T_ambient.to("K").value,
        T_cloud=T_cloud.to("K").value,
        cloud_radius_factor=CLOUD_RADIUS_FACTOR,
        velocity_cloud=v_cloud.to("km / s").value,
    )

    today = datetime.now().strftime("%Y-%m-%d-%H:%M:%S")
    print("##########################################################")
    print("## Problem setup")
    print("# Generated by ./script/generate_moving_cloud_ic.py")
    print("# On: {}".format(today))
    print(problem_block)
    print()
    print(unit_block)
    print("# End of generated block")
    print("##########################################################")


def main():
    args = parse_args()
    ## Input parameters:
    rho_ambient = 1e-3 * u.mh / u.cm**3
    temperature_ambient = 2e6 * u.K
    temperature_cloud = 1e4 * u.K
    mass_cloud = 1e6 * u.Msun
    velocity_cloud = 70 * u.km / u.s

    ## Derive code units
    rho_cloud = rho_ambient * temperature_ambient / temperature_cloud
    radius_cloud = (mass_cloud / ((4 / 3) * np.pi * rho_cloud)) ** (1 / 3)
    length_unit = CLOUD_RADIUS_FACTOR * radius_cloud.to("cm")
    mass_unit = (rho_ambient * length_unit**3).to("g")

    # Derive time unit from velocity unit (1 km / s ~ 1 kpc / Gyr)
    velocity_unit = 1 * u.km / u.s
    time_unit = (length_unit / velocity_unit).to("s")

    # Derived units (not really used)
    energy_unit = (mass_unit * (length_unit / time_unit) ** 2).to("erg")
    pressure_unit = (energy_unit / length_unit**3).to("erg / cm**3")

    ########## Some pixel things
    pixel_per_unit_length = 16
    max_refinement_level = 3
    pc_per_pixel = (length_unit / pixel_per_unit_length).to("pc")

    ## Print everything with a hash:
    if args.print_resolution:
        print(f"With {pixel_per_unit_length} pixels per unit length")
        print(f"And unit length {length_unit.to('kpc'):.2f}, the resolution is:")
        for ref_level in range(0, max_refinement_level + 1):
            pc_per_pixel_refined = pc_per_pixel / (2**ref_level)
            print(
                f"At refinement level {ref_level}, pixel size = {pc_per_pixel_refined:.2f}"
            )

    print_initial_conditions(
        length_unit,
        mass_unit,
        time_unit,
        rho_ambient,
        temperature_ambient,
        temperature_cloud,
        velocity_cloud,
    )


import argparse


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--print-resolution",
        action="store_true",
        help="Print the spatial resolution at different refinement levels",
    )
    # TODO: add these later
    # parser.add_argument("rho_ambient", type=float, help="")
    # parser.add_argument("cloud_mass", type=float, help="")
    # parser.add_argument("temperature_hot", type=float, help="")
    parser.add_argument(
        "-v", "--verbose", action="store_true", help="increase output verbosity"
    )
    return parser.parse_args()


if __name__ == "__main__":
    main()
